version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      kubernetes-and-helm:
        patterns:
          - k8s.io/*
          - sigs.k8s.io/*
          - helm.sh/*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
