'use strict';
const token = new URLSearchParams(location.hash.slice(1)).get('token') || '';
history.replaceState(null, '', location.pathname);
const element = (tag, text, cls) => { const e = document.createElement(tag); if (text !== undefined) e.textContent = text; if(cls) e.className = cls; return e; };
const set = (id, text) => { document.getElementById(id).textContent = text; };
function rows(id, items) { const target=document.getElementById(id);target.replaceChildren(); if(!items.length)target.append(element('p','No requests in this namespace.','muted'));for(const item of items){const row=element('div',undefined,'row');row.append(element('strong',item.name),element('span',item.phase,'badge'));if(item.message)row.append(element('p',item.message));if(item.expires)row.append(element('small','Expires '+new Date(item.expires).toLocaleString()));target.append(row);} }
const expanded = new Set();
let refreshing = false;
function replica(r,namespace){const card=element('article',undefined,'replica');const head=element('div',undefined,'section-title');head.append(element('h3',r.name),element('span',r.phase||'Pending','badge '+(r.phase==='Ready'?'good':'')));card.append(head);
const steps=['Capture','Provision','Prepare data','Replicate','Verify','Ready'];const phase={Capturing:0,AwaitingApproval:0,Queued:0,Provisioning:1,Connecting:1,PreparingData:2,Restoring:2,Replicating:3,Refreshing:3,Verifying:4,Ready:5};const timeline=element('div',undefined,'timeline');steps.forEach((name,i)=>timeline.append(element('span',name,i<=(phase[r.phase]??-1)?'done':'')));card.append(timeline);
if(r.phase==='Deleting'||r.phase==='Expired'||r.phase==='Cleaned')card.append(element('p',r.phase==='Deleting'?'Cleanup in progress — finalizers are still verifying owned resources.':'Lifecycle finished.','muted'));
card.append(element('p','Plan '+(r.revision?r.revision.slice(0,16)+'…':'not captured')+' · '+(r.resources||[]).length+' objects','muted'));
const details=element('details');const key=r.uid||r.name;details.open=expanded.has(key);details.addEventListener('toggle',()=>{if(details.open)expanded.add(key);else expanded.delete(key);});details.append(element('summary','Inspect dependencies and validation'));for(const f of r.findings||[])details.append(element('p','['+f.result+'] '+f.check+': '+f.detail));for(const o of r.resources||[]){const row=element('div',undefined,'resource');row.append(element('strong',o.kind+' '+o.sourceNamespace+'/'+(o.sourceName||o.name)),element('span',' → '+o.namespace+'/'+o.name));if(o.dependencies?.length)row.append(element('small','Requires: '+o.dependencies.join(', ')));if(o.transformations?.length)row.append(element('small','Changes: '+o.transformations.join(', ')));details.append(row);}card.append(details);
const cmd=element('code','replicove plan '+r.name+' --namespace '+namespace);const copy=element('button','Copy inspect command');copy.type='button';copy.addEventListener('click',()=>navigator.clipboard.writeText(cmd.textContent).then(()=>copy.textContent='Copied').catch(()=>copy.textContent='Select command to copy'));card.append(cmd,copy);return card;}
async function refresh(){if(refreshing)return;refreshing=true;try{const response=await fetch('/api/status',{headers:{'X-Replicove-Token':token},cache:'no-store'});if(!response.ok)throw new Error(response.status===401?'Open the complete URL printed by replicove dashboard.':'Dashboard data unavailable ('+response.status+').');const data=await response.json();set('connection','● Live');set('namespace',data.namespace);set('updated','Updated '+new Date(data.updated).toLocaleTimeString());set('count',data.replicas.length);set('ready',data.replicas.filter(r=>r.phase==='Ready').length);set('attention',data.replicas.filter(r=>['Blocked','Rejected','PreparingData'].includes(r.phase)).length);set('active',data.experiments.filter(x=>x.phase==='Active').length);document.getElementById('warnings').replaceChildren(...(data.warnings||[]).map(w=>element('p',w,'warning')));const target=document.getElementById('replicas');target.replaceChildren(...data.replicas.map(r=>replica(r,data.namespace)));if(!data.replicas.length)target.append(element('p','No replicas yet. Create a request with the CLI or a Kubernetes manifest.','empty'));rows('mirrors',data.mirrors);rows('experiments',data.experiments);}catch(e){set('connection','○ Offline');document.getElementById('warnings').replaceChildren(element('p',e.message,'warning'));}finally{refreshing=false;}}
refresh();setInterval(refresh,5000);
