// Render the native installer from the same embedded chart as the CLI.
package main

import (
	"fmt"
	"io/fs"
	"os"
	"sort"
	"strings"

	operatorchart "github.com/nimeshbuilds/cluster-replica/charts/replicove"
	"helm.sh/helm/v4/pkg/chart/common"
	"helm.sh/helm/v4/pkg/chart/common/util"
	"helm.sh/helm/v4/pkg/chart/loader/archive"
	"helm.sh/helm/v4/pkg/chart/v2/loader"
	"helm.sh/helm/v4/pkg/engine"
)

func main() {
	var files []*archive.BufferedFile
	check(fs.WalkDir(operatorchart.Files, ".", func(path string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		data, err := operatorchart.Files.ReadFile(path)
		files = append(files, &archive.BufferedFile{Name: path, Data: data})
		return err
	}))
	chart, err := loader.LoadFiles(files)
	check(err)
	values, err := util.ToRenderValues(chart, map[string]any{"createDestinationNamespace": false, "stateKey": map[string]any{"bootstrap": true}}, common.ReleaseOptions{Name: "replicove", Namespace: "replicove-system", IsInstall: true}, nil)
	check(err)
	rendered, err := engine.Render(chart, values)
	check(err)
	names := make([]string, 0, len(rendered))
	for name := range rendered {
		names = append(names, name)
	}
	sort.Strings(names)
	var out strings.Builder
	out.WriteString("# Generated by make manifests. Edit charts/replicove, then regenerate.\n")
	for _, name := range names {
		if strings.TrimSpace(rendered[name]) == "" {
			continue
		}
		out.WriteString("---\n# Source: " + name + "\n" + strings.TrimSpace(rendered[name]) + "\n")
	}
	check(os.WriteFile("config/install/operator.yaml", []byte(out.String()), 0644))
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
