apiVersion: replica.nimeshbuilds.dev/v1alpha1
kind: ReplicaGrant
metadata:
  name: mirror-lab
spec:
  targetNamespace: replica-lab
  sourceNamespaces: [source-dev]
  resources:
    - {group: '', kind: PersistentVolumeClaim}
    - {group: '', kind: ConfigMap}
    - {group: apps, kind: Deployment}
  allowEmptyVolumes: true
  maxTTL: 3h
  accessRoles: [viewer, deployer, admin]
  maxAccessSeconds: 3600
  mirror:
    minInterval: 1m
    maxRevisions: 3
    allowForcedReset: true
    volumes:
      - namespace: source-dev
        name: orders-data
        snapshotClass: csi-hostpath-snapclass
        storageClass: mirror-csi
